name: docker-build

on:
  push:
    branches:
      - main

jobs:
  multi-arch-push:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - 
        name: Login to GitHub Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GH_PAT }}
      -
         name: Get Latest Tag
         id: previoustag
         uses: WyriHaximus/github-action-get-previous-tag@04e8485ecb6487243907e330d522ff60f02283ce # pin@v1.4.0
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/386,linux/arm64,linux/arm/v7,linux/arm/v6,linux/s390x,linux/ppc64le,linux/riscv64
          push: true
          tags: |
            ghcr.io/erisa/ts-derper:latest
            ghcr.io/erisa/ts-derper:${{ steps.previoustag.outputs.tag }}
          cache-from: type=gha,mode=max
          cache-to: type=gha,mode=max
